name: Build OVMF

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OVMF
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      TOOLCHAIN: CLANG9
      build_target: RELEASE
      stuart_opts: -c OvmfPkg/PlatformCI/PlatformBuild.py -a X64 Target=RELEASE TOOL_CHAIN_TAG=CLANG9 BLD_*_NETWORK_HTTP_ENABLE=1 BLD_*_TPM1_ENABLE=1 BLD_*_TPM2_ENABLE=1

    steps:
      - name: Get Latest EDK-II Release
        run: |
          echo "REF=$(curl -s https://api.github.com/repos/tianocore/edk2/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Update System and Install Dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install uuid-dev iasl nasm

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          repository: tianocore/edk2
          ref: ${{ env.REF }}
          path: main
          submodules: recursive

      - name: Setup Dependencies
        working-directory: ${{ github.workspace }}/main
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r pip-requirements.txt --upgrade
          python BaseTools/Edk2ToolsBuild.py -t "${toolchain}"

      - name: Build OVMF
        working-directory: ${{ github.workspace }}/main
        run: |
          source .venv/bin/activate
          stuart_setup ${stuart_opts} && stuart_update ${stuart_opts} && stuart_build ${stuart_opts}

      - name: Create Release .tar.xz
        working-directory: ${{ github.workspace }}
        run: |
          mkdir package
          
          cp main/Build/OvmfX64/RELEASE_CLANG9/FV/OVMF_CODE.fd package/
          cp main/Build/OvmfX64/RELEASE_CLANG9/FV/OVMF_VARS.fd package/
          cp main/Build/OvmfX64/RELEASE_CLANG9/X64/Shell.efi package/

          tar cf package.tar package/
          xz package.tar

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REF }}-run${{ github.run_number }}
          name: ${{ env.REF }}-run${{ github.run_number }}
          files: ${{ github.workspace }}/package.tar.xz
