name: Build OVMF

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OVMF
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      
    steps:
      - name: Installing Dependencies and Updating System
        run: |
          sudo apt update
          sudo apt upgrade
          
          sudo apt install nasm m4 bison flex uuid-dev unzip iasl gcc-multilib

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          repository: tianocore/edk2
          ref: ${{ env.REF }}
          path: main
          submodules: recursive

      - name: Setup Build Environment
        working-directory: ${{ github.workspace }}/main
        run: |
          git submodule update --init --recursive
          
          echo "*venv*/**" >> .git/info/exclude
          
          python -m venv .venv
          source .venv/bin/activate

          pip install -r pip-requirements.txt --upgrade

          python BaseTools/Edk2ToolsBuild.py -t GCC5

      - name: Build
        working-directory: ${{ github.workspace }}/main
        run: |
          stuart_setup -c OvmfPkg/PlatformCI/PlatformBuild.py -a X64 Target=RELEASE TOOL_CHAIN_TAG=GCC5 BLD_*_NETWORK_HTTP_ENABLE=1 BLD_*_TPM1_ENABLE=1 BLD_*_TPM2_ENABLE=1
          stuart_update -c OvmfPkg/PlatformCI/PlatformBuild.py -a X64 Target=RELEASE TOOL_CHAIN_TAG=GCC5 BLD_*_NETWORK_HTTP_ENABLE=1 BLD_*_TPM1_ENABLE=1 BLD_*_TPM2_ENABLE=1
          stuart_build -c OvmfPkg/PlatformCI/PlatformBuild.py -a X64 Target=RELEASE TOOL_CHAIN_TAG=GCC5 BLD_*_NETWORK_HTTP_ENABLE=1 BLD_*_TPM1_ENABLE=1 BLD_*_TPM2_ENABLE=1

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REF }}-run${{ github.run_number }}
          name: ${{ env.REF }}-run${{ github.run_number }}
          files: ${{ github.workspace }}/main/Build/**/*
