name: Build OVMF

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OVMF
    runs-on: ubuntu-latest
    container: archlinux:latest
    permissions:
      contents: write

    steps:
      - name: Install Dependencies and Update System
        run: |
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --noconfirm "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst" "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst"
          echo "[chaotic-aur]"                              >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

          pacman -Syu --noconfirm
          pacman -S --noconfirm mono nasm jq git acpica python make llvm-git lld-git clang-git

      - name: Get Latest EDK-II Release
        run: |
          echo "REF=$(curl -s https://api.github.com/repos/tianocore/edk2/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          repository: tianocore/edk2
          ref: ${{ env.REF }}
          path: main
          submodules: recursive

      - name: Build
        working-directory: ${{ github.workspace }}/main
        run: |
          python -m venv .venv
          source .venv/bin/activate

          pip install -r pip-requirements.txt --upgrade

          python BaseTools/Edk2ToolsBuild.py -t GCC

          stuart_setup ${{ env.stuart_opts }}
          stuart_update ${{ env.stuart_opts }}
          stuart_build ${{ env.stuart_opts }}
        env:
          stuart_opts: -c OvmfPkg/PlatformCI/PlatformBuild.py -a X64 Target=RELEASE TOOL_CHAIN_TAG=CLANGDWARF BLD_*_NETWORK_HTTP_ENABLE=1 BLD_*_TPM1_ENABLE=1 BLD_*_TPM2_ENABLE=1

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: ${{ env.REF }}-run${{ github.run_number }}
          name: ${{ env.REF }}-run${{ github.run_number }}
          files: |
            ${{ github.workspace }}/main/Build/OvmfX64/RELEASE_CLANGDWARF/FV/OVMF_CODE.fd
            ${{ github.workspace }}/main/Build/OvmfX64/RELEASE_CLANGDWARF/FV/OVMF_VARS.fd
