name: Build OVMF

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OVMF
    runs-on: ubuntu-latest
    container: archlinux:latest
    permissions:
      contents: write    
      
    steps:
      - name: Install Dependencies and Update System
        run: |
          pacman -Syu --noconfirm
          pacman-key --init
          
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst" --noconfirm
          pacman -U "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst" --noconfirm
          echo "[chaotic-aur]"                              >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
          
          pacman -Syu jq git nasm acpica python make llvm-git lldb-git lld-git polly-git compiler-rt-git clang-git llvm-libs-git --noconfirm

      - name: Get Latest EDK-II Release
        run: |
          echo "REF=$(curl -s https://api.github.com/repos/tianocore/edk2/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          repository: tianocore/edk2
          ref: ${{ env.REF }}
          path: main
          submodules: recursive

      - name: Build
        working-directory: ${{ github.workspace }}/main
        run: |
          make -C BaseTools
          cd ${{ github.workspace }}/main
          source edksetup.sh

          echo "EDK_TOOLS_PATH=${{ github.workspace }}/main/BaseTools" >> $GITHUB_ENV

          make -C edk2/BaseTools
          cd ${{ github.workspace }}/main
          source edksetup.sh BaseTools

          sed -i "" "s|Nt32Pkg/Nt32Pkg.dsc|OvmfPkg/OvmfPkgX64.dsc|g" Conf/target.txt
          sed -i "" "s|MYTOOLS|CLANGDWARF|g" Conf/target.txt
          sed -i "" "s|IA32|X64|g" Conf/target.txt
          
          build -p OvmfPkg/OvmfPkgX64.dsc -b RELEASE -a X64 -t CLANGDWARF -D TPM_ENABLE -D TPM_CONFIG_ENABLE -D SECURE_BOOT_ENABLE -D NETWORK_TLS_ENABLE

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: ${{ env.REF }}-run${{ github.run_number }}
          name: ${{ env.REF }}-run${{ github.run_number }}
          files: ${{ github.workspace }}/main/Build/OvmfX64/RELEASE_CLANGDWARF/FV/*
